name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: ${version}
api-version: '1.20'
authors: [sgtcaze, Cory, Lorenzo0111, Aurelien30000]
softdepend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]
folia-supported: true

commands:
  ne:
    description: NametagEdit commands
    permission: nametagedit.use
    aliases: [nte, nametagedit]
